In [1]:
import numpy as np
import random

In [ ]:
# 1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of functions and methods that allows you to perform many actions without writing your own code. These libraries are 
written in Python or other languages, such as C or C++, and are imported into your Python code, enabling you to use their functionality.

We use Python libraries for several reasons:
1. Reuse of codes.
2. Efficiency
3. Specialized functionality
4. Community support
5. Interoperabilityproblems.

Python standard library : Pandas, Numpy, TensorFlow, Matplotlib, SciPy, PyTorch
Overall, Python libraries are essential for expanding the capabilities of Python and making it a powerful tool for a wide range of tasks,
from web development to data analysis, machine learning, scientific computing, and more.

In [ ]:
# 2. What is the difference between Numpy array and List?

1. Data Types:
    NumPy arrays are homogeneous, meaning all elements of an array must be of the same data type (e.g., integers, floats, etc.). This allows for more
    efficient storage and operations on the data.
    Python lists can contain elements of different data types, making them more flexible but potentially less efficient for numerical computations.

2. Memory Usage:
    NumPy arrays typically use less memory compared to Python lists, especially for large datasets, because they store data in a contiguous block of 
    memory.
    Python lists are more flexible in terms of memory usage, as they can dynamically resize and store different types of objects, but this flexibility 
    comes with additional memory overhead.

3. Performance: 
    NumPy arrays are optimized for numerical computations, with efficient element-wise operations and mathematical functions. These operations are 
    implemented in C, resulting in faster performance than equivalent operations on lists

    Lists are not optimized for numerical computations and may have slower mathematical operations due to Python’s interpretation overhead. 
    They are generally used as general-purpose data structures.



In [4]:
'''
3. Find the shape, size and dimension of the following array?
[[1,2,3,4]
[5,6,7,8],
[9,10,11,12]]

'''

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("Shape os the array: ",arr.shape)
print("Dimension of teh arr: ",arr.ndim)

Shape os the array:  (3, 4)
Dimension of teh arr:  2


In [ ]:
'''
4. Write python code to access the first row of the following array?

[[1,2,3,4]
[5, 6, 7, 8],
[9,10,11,12]]

'''
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)
arr[0]

In [5]:
'''
5. How do you access the element at the third row and fourth column from the given numpy array?

[[1,2,3,4]
[5,6,7,8],
[9,10,11,12]]

'''
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr[2,3]

12

In [6]:
'''
6. Write code to extract all odd-indexed elements from the given numpy array?

[[1,2,3,4],
[5, 6, 7, 8],
[9,10,11,12]]

'''
arr[:, [1,3]]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [7]:
# 7. How can you generate a random 3x3 matrix with values between 0 and 1?
arr1 = np.random.rand(3,3)
arr1

array([[0.95143893, 0.54265894, 0.20466385],
       [0.85197994, 0.25080074, 0.63474072],
       [0.04478136, 0.07499691, 0.43914336]])

In [8]:
# 8. Describe the difference between np.random.rand and np.random.randn?

''' np.random.randn generates samples from the normal distribution, while np.random.rand from a uniform distribution '''

a1 = np.random.rand(2,3)
print("Uniform distribution: \n",a1)
a2 = np.random.randn(2,3)  #normal distribution
print("Normal distribution: \n",a2)


Uniform distribution: 
 [[0.53066638 0.05360121 0.27885386]
 [0.50448664 0.62287672 0.33791098]]
Normal distribution: 
 [[-0.28786527 -0.86167604 -0.43574361]
 [ 0.08047494  1.34479093  2.42190489]]


In [9]:
'''
9. Write code to increase the dimension of the following array?

[[1,2,3,4]
[5,6,7,8],
[9,10,11,12]]

'''
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("initials dimension: ", arr.ndim)
arr = np.expand_dims(arr, axis = 0)
print("\nNew dimension: ", arr.ndim)
print(arr)


initials dimension:  2

New dimension:  3
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [10]:
'''
10. How to transpose the following array in NumPy?

[[1,2,3,4]
[5,6,7,8],
[9,10,11,12]]
'''
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("Original array: \n",arr)
print("\nTranspose array: \n",arr.T)


Original array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transpose array: 
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [11]:
'''
11. Consider the following matrix:

Matrix A: [[1,2,3,4] [5, 6, 7, 8], [9, 10, 11, 12]] Matrix B: [[1,2,3,4][5,6,7,8],[9,10,11,12]]

Perform the following operation using Python:

1. Index wise multiplication

2. Matrix multiplication

3. Add both the matrics

4. Subtract matrix B from A

5. Divide Matrix B by A

'''
A = np.array([[1,2,3,4], [5, 6, 7, 8], [9, 10, 11, 12]])
B = np.array([[1,2,3,4], [5, 6, 7, 8], [9,10,11,12]])

print("Index wise multiplication: \n", A * B)

#print("Matrix multiplication: \n", A@B) #Matrix multiplicaion not possible -> size 3 is different from 4

print("\nAdd both the matrics: \n", A+B)
print("\nSubtract matrix B from A: \n", A-B)
print("\nDivide Matrix B by A : \n", B/A)



Index wise multiplication: 
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

Add both the matrics: 
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Subtract matrix B from A: 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Divide Matrix B by A : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
# 12. Which function in Numpy can be used to swap the byte order of an array?

arr1 = np.array([1,4,3,2], dtype = np.int16)
arr1.byteswap(inplace=True)

array([ 256, 1024,  768,  512], dtype=int16)

In [ ]:
# 13. What is the significance of the np.linalg.inv function?

''' We use np.linalg.inv() function to calculate the inverse of a matrix '''
from numpy.linalg import inv

A = np.array([[1,2,3,4], [5, 6, 7, 8], [9, 10, 11, 12]])
B = np.linalg.inv(A)
print(A)
print(B)

In [13]:
# 14. What does the np.reshape function do, and how is it used?
''' reshape() function is used to create a new array of the same size (as the original array) but of different desired dimensions '''
arr = np.random.randint(1,5, size = (3, 4))
arr

array([[3, 2, 2, 2],
       [3, 4, 3, 4],
       [4, 2, 2, 3]])

In [14]:
arr.size

12

In [15]:
arr.reshape(2,6)

array([[3, 2, 2, 2, 3, 4],
       [3, 4, 4, 2, 2, 3]])

In [16]:
arr.reshape(4,3)

array([[3, 2, 2],
       [2, 3, 4],
       [3, 4, 4],
       [2, 2, 3]])

In [17]:
# 15. What is broadcasting in Numpy?

''' The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. '''

arr1 = np.ones((3,4))
arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
arr1 +3

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [19]:
arr1 * 6

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])